name: Run Shell Script  File

on: push

jobs:
    shell_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: List Repo File
              run: ls -la    
              
            - name: Executing Shell Script
              run: |
                chmod +x ascii-scripts.sh
                ./ascii-scripts.sh
